version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo $CODEBUILD_SRC_DIR
      - # Install NestJS and Angular cli so we can build both
      - npm install -g @nestjs/cli
      - npm install -g @angular/cli
  pre_build:
    commands:
      - # Update our node_modules for the api project.
      - # Don't need to audit here, as we audit on workstation client
      - npm install --no-audit
      - # Move into our frontend directory
      - cd app
      - # Install frontend node_modules
      - npm install --no-audit
  build:
    commands:
      - # Move up one directory to our root
      - cd ../
      - # Build the backend
      - npm run build
      - # Move back into our frontend directory
      - cd app
      - # Build the Angular UI with prod settings
      - npm run build-prod
  post_build:
    commands:
      - echo No post_build steps for now...
artifacts:
  files:
    - 'dist/**/*'
    - 'public/**/*'
    - 'node_modules/**/*'
    - 'package.json'
    - 'Procfile'
